// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Episode struct {
	ID              uuid.UUID  `json:"id"`
	SeriesID        uuid.UUID  `json:"series_id"`
	Title           string     `json:"title"`
	Description     *string    `json:"description"`
	DurationSeconds *int32     `json:"duration_seconds"`
	PublishDate     *time.Time `json:"publish_date"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type EpisodeAsset struct {
	ID        uuid.UUID `json:"id"`
	EpisodeID uuid.UUID `json:"episode_id"`
	AssetType string    `json:"asset_type"`
	MimeType  string    `json:"mime_type"`
	SizeBytes *int64    `json:"size_bytes"`
	Url       *string   `json:"url"`
	Storage   []byte    `json:"storage"`
	CreatedAt time.Time `json:"created_at"`
}

type Series struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	CategoryID  uuid.UUID  `json:"category_id"`
	Language    *string    `json:"language"`
	SeriesType  string     `json:"series_type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}
