// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Categories
	CountCategories(ctx context.Context) (int64, error)
	// Episodes
	CountEpisodesBySeries(ctx context.Context, seriesID uuid.UUID) (int64, error)
	// Series
	CountSeries(ctx context.Context) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (EpisodeAsset, error)
	CreateCategory(ctx context.Context, slug string) (Category, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	DeleteAsset(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteEpisode(ctx context.Context, id uuid.UUID) error
	DeleteSeries(ctx context.Context, id uuid.UUID) error
	GetAsset(ctx context.Context, id uuid.UUID) (EpisodeAsset, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetEpisode(ctx context.Context, id uuid.UUID) (Episode, error)
	GetEpisodeWithAssets(ctx context.Context, id uuid.UUID) ([]GetEpisodeWithAssetsRow, error)
	GetSeries(ctx context.Context, id uuid.UUID) (Series, error)
	// Episode Assets
	ListAssetsByEpisode(ctx context.Context, episodeID uuid.UUID) ([]EpisodeAsset, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]Category, error)
	ListEpisodesBySeries(ctx context.Context, seriesID uuid.UUID) ([]Episode, error)
	ListEpisodesBySeriesPaginated(ctx context.Context, arg ListEpisodesBySeriesPaginatedParams) ([]Episode, error)
	ListEpisodesWithAssetsBySeriesPaginated(ctx context.Context, arg ListEpisodesWithAssetsBySeriesPaginatedParams) ([]ListEpisodesWithAssetsBySeriesPaginatedRow, error)
	ListSeries(ctx context.Context) ([]Series, error)
	ListSeriesPaginated(ctx context.Context, arg ListSeriesPaginatedParams) ([]Series, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (EpisodeAsset, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error)
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error)
}

var _ Querier = (*Queries)(nil)
